# Generated by Django 3.2.3 on 2021-06-21 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30, verbose_name='Autor')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de Noticias Subidas')),
                ('colaboradores', models.CharField(blank=True, max_length=50, null=True, verbose_name='Colaboradores')),
                ('correo', models.EmailField(max_length=60, verbose_name='Correo electrónico')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
