# Generated by Django 3.2.3 on 2021-06-23 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210621_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='cantidad',
            new_name='cantidadNoticias',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='autor',
            new_name='nombreNoticias',
        ),
    ]
