# Generated by Django 3.2.3 on 2021-06-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210623_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodista',
            name='contrasena',
            field=models.CharField(default=1, max_length=35, verbose_name='Contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodista',
            name='correo',
            field=models.CharField(default=1, max_length=60, unique=True, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
    ]
