# Generated by Django 3.2.3 on 2021-06-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_correoelec_periodista_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodista',
            name='correo',
            field=models.EmailField(max_length=60, verbose_name='Correo electrónico'),
        ),
    ]
