# Generated by Django 3.2.3 on 2021-06-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(max_length=50, verbose_name='Nombre de la Noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='colaboradores',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autor'),
        ),
    ]
