# Generated by Django 3.2.3 on 2021-06-24 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210623_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('run', models.IntegerField(primary_key=True, serialize=False, verbose_name='Run de Periodista')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombre Periodista')),
            ],
        ),
        migrations.RemoveField(
            model_name='noticiass',
            name='cantidadNoticias',
        ),
        migrations.RemoveField(
            model_name='noticiass',
            name='colaboradores',
        ),
        migrations.RemoveField(
            model_name='noticiass',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='noticiass',
            name='nombreNoticias',
        ),
        migrations.AddField(
            model_name='noticiass',
            name='fecha',
            field=models.CharField(default=1, max_length=30, verbose_name='Fecha '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticiass',
            name='historia',
            field=models.CharField(default=1, max_length=100, verbose_name='Historia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticiass',
            name='titulo',
            field=models.CharField(default=1, max_length=50, verbose_name='Título Noticia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticiass',
            name='ubicacion',
            field=models.CharField(default=1, max_length=50, verbose_name='Ubicación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticiass',
            name='idNoticia',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Noticia'),
        ),
        migrations.AddField(
            model_name='noticiass',
            name='periodista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.periodista'),
            preserve_default=False,
        ),
    ]
