# Generated by Django 3.2.3 on 2021-06-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210624_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodista',
            name='correo',
        ),
        migrations.AddField(
            model_name='periodista',
            name='correoelec',
            field=models.CharField(default=1, max_length=60, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
    ]
