# Generated by Django 3.2.3 on 2021-06-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210624_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodista',
            old_name='correoelec',
            new_name='correo',
        ),
    ]
